export const API_URL = "https://abdellah-ennajari-23--llama3-openai-compatible-serve.modal.run";

export const LANGUAGES = [
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'ar', label: 'العربية', flag: '🇲🇦' },
  { code: 'en', label: 'English', flag: '🇬🇧' }
];

export const DRAWER_WIDTH = 300;
export const COLLAPSED_DRAWER_WIDTH = 72;

export const translations = {
  fr: {
    newChat: "Nouveau chat",
    settings: "Paramètres",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    autoRead: "Lecture automatique des réponses",
    languageSection: "Langue",
    close: "Fermer",
    writeMessage: "Écrivez votre message...",
    thinking: "Réflexion en cours...",
    newConversation: "Nouvelle conversation",
    edit: "Modifier",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    startRecording: "Enregistrer un message audio",
    stopRecording: "Arrêter l'enregistrement",
    assistant: "Assistant Académique ENIAD",
    startPrompt: "Posez votre question ou choisissez un sujet ci-dessous pour commencer une nouvelle conversation.",
    errorMessage: "Désolé, une erreur est survenue. Veuillez réessayer.",
    disclaimer: "ENIAD AI peut faire des erreurs. Vérifiez les informations importantes.",
    version: "v1.0.0",
    suggestions: [
      "Quels sont les programmes de formation disponibles à l'ENIAD ?",
      "Comment puis-je m'inscrire à l'ENIAD ?",
      "Quelles sont les conditions d'admission à l'ENIAD ?",
    ],
    usingSystemPreference: "Utilise les préférences système",
    editTitle: "Modifier le titre de la conversation",
    contextTitle: "Contexte: ",
    login: "Se connecter",
    logout: "Se déconnecter",
    contact: "Nous contacter",
    // Settings dialog specific translations
    settingsTitle: "Paramètres",
    customizeExperience: "Personnalisez votre expérience",
    appearance: "Apparence",
    switchThemes: "Basculer entre les thèmes clair et sombre",
    audioSettings: "Paramètres audio",
    readAloud: "Lecture automatique des réponses",
    autoReadDescription: "Lire automatiquement les réponses de l'assistant à voix haute",
    language: "Langue",
    about: "À propos",
    poweredBy: "Alimenté par une technologie IA moderne pour des expériences d'apprentissage améliorées.",
    expand: "Développer la barre latérale",
    collapse: "Réduire la barre latérale",
    chatHistory: "Historique",
    you: "Vous",
    speak: "Lire à haute voix",
    copy: "Copier",
    copied: "Copié !",
    copiedToClipboard: "Copié dans le presse-papiers !",
    // RAG System
    ragSystem: "Système RAG",
    ragHealthy: "Système RAG en ligne",
    ragUnhealthy: "Problèmes système RAG",
    ragError: "Erreur système RAG",
    ragUnknown: "Statut RAG inconnu",
    checking: "Vérification...",
    endpoint: "Point de terminaison",
    projectId: "ID du projet",
    indexInfo: "Info de l'index",
    lastCheck: "Dernière vérification",
    ragStatusHelp: "Ceci montre l'état de connexion à votre système RAG_Project. Assurez-vous que votre serveur FastAPI fonctionne sur le point de terminaison configuré.",
    // SMA System
    smaActive: "SMA Activé - Intelligence Web en temps réel",
    smaInactive: "Activer SMA - Surveillance intelligente des sites",
    smaSearching: "SMA en cours de recherche...",
    smaEnhanced: "Réponse enrichie par SMA",
    smaWebIntelligence: "Intelligence Web SMA",
    smaRealTimeData: "Données en temps réel d'ENIAD et UMP",
  },
  en: {
    newChat: "New Chat",
    settings: "Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    autoRead: "Auto-read responses",
    languageSection: "Language",
    close: "Close",
    writeMessage: "Write your message...",
    thinking: "Thinking...",
    newConversation: "New Conversation",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    startRecording: "Record audio message",
    stopRecording: "Stop recording",
    assistant: "ENIAD Academic Assistant",
    startPrompt: "Ask your question or choose a topic below to start a new conversation.",
    errorMessage: "Sorry, an error occurred. Please try again.",
    disclaimer: "ENIAD AI may make mistakes. Please verify important information.",
    version: "v1.0.0",
    suggestions: [
      "What training programs are available at ENIAD?",
      "How can I enroll at ENIAD?",
      "What are the admission requirements for ENIAD?",
    ],
    usingSystemPreference: "Using system preference",
    editTitle: "Edit conversation title",
    contextTitle: "Context: ",
    login: "Login",
    logout: "Log out",
    contact: "Contact us",
    expand: "Expand sidebar",
    collapse: "Collapse sidebar",
    chatHistory: "Chat History",
    you: "You",
    speak: "Read aloud",
    copy: "Copy",
    copied: "Copied!",
    copiedToClipboard: "Copied to clipboard!",
    // Settings dialog specific translations
    settingsTitle: "Settings",
    customizeExperience: "Customize your experience",
    appearance: "Appearance",
    switchThemes: "Switch between light and dark themes",
    audioSettings: "Audio Settings",
    readAloud: "Auto-read responses",
    autoReadDescription: "Automatically read assistant responses aloud",
    language: "Language",
    about: "About",
    poweredBy: "Powered by modern AI technology for enhanced learning experiences.",
    // RAG System
    ragSystem: "RAG System",
    ragHealthy: "RAG System Online",
    ragUnhealthy: "RAG System Issues",
    ragError: "RAG System Error",
    ragUnknown: "RAG Status Unknown",
    checking: "Checking...",
    endpoint: "Endpoint",
    projectId: "Project ID",
    indexInfo: "Index Info",
    lastCheck: "Last Check",
    ragStatusHelp: "This shows the connection status to your RAG_Project system. Make sure your FastAPI server is running on the configured endpoint.",
    // SMA System
    smaActive: "SMA Active - Real-time Web Intelligence",
    smaInactive: "Activate SMA - Smart Website Monitoring",
    smaSearching: "SMA searching...",
    smaEnhanced: "SMA-enhanced response",
    smaWebIntelligence: "SMA Web Intelligence",
    smaRealTimeData: "Real-time data from ENIAD and UMP",
  },
  ar: {
    newChat: "محادثة جديدة",
    settings: "الإعدادات",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    autoRead: "قراءة تلقائية للردود",
    languageSection: "اللغة",
    close: "إغلاق",
    writeMessage: "اكتب رسالتك...",
    thinking: "جاري التفكير...",
    newConversation: "محادثة جديدة",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    startRecording: "تسجيل رسالة صوتية",
    stopRecording: "إيقاف التسجيل",
    assistant: "المساعد الأكاديمي ENIAD",
    startPrompt: "اطرح سؤالك أو اختر موضوعًا أدناه لبدء محادثة جديدة.",
    errorMessage: "عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.",
    disclaimer: "قد يرتكب ENIAD AI أخطاء. يرجى التحقق من المعلومات المهمة.",
    version: "الإصدار 1.0.0",
    suggestions: [
      "ما هي البرامج التدريبية المتاحة في ENIAD؟",
      "كيف يمكنني التسجيل في ENIAD؟",
      "ما هي شروط القبول في ENIAD؟",
    ],
    usingSystemPreference: "يستخدم تفضيلات النظام",
    editTitle: "تعديل عنوان المحادثة",
    contextTitle: "السياق: ",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    contact: "اتصل بنا",
    expand: "توسيع الشريط الجانبي",
    collapse: "طي الشريط الجانبي",
    chatHistory: "تاريخ المحادثات",
    you: "أنت",
    speak: "قراءة بصوت عالٍ",
    copy: "نسخ",
    copied: "تم النسخ!",
    copiedToClipboard: "تم النسخ إلى الحافظة!",
    // Settings dialog specific translations
    settingsTitle: "الإعدادات",
    customizeExperience: "تخصيص تجربتك",
    appearance: "المظهر",
    switchThemes: "التبديل بين الأوضاع الفاتحة والداكنة",
    audioSettings: "إعدادات الصوت",
    readAloud: "قراءة تلقائية للردود",
    autoReadDescription: "قراءة ردود المساعد تلقائياً بصوت عالٍ",
    language: "اللغة",
    about: "حول",
    poweredBy: "مدعوم بتقنية الذكاء الاصطناعي الحديثة لتجارب تعليمية محسّنة.",
    // RAG System
    ragSystem: "نظام RAG",
    ragHealthy: "نظام RAG متصل",
    ragUnhealthy: "مشاكل في نظام RAG",
    ragError: "خطأ في نظام RAG",
    ragUnknown: "حالة RAG غير معروفة",
    checking: "جاري التحقق...",
    endpoint: "نقطة النهاية",
    projectId: "معرف المشروع",
    indexInfo: "معلومات الفهرس",
    lastCheck: "آخر فحص",
    ragStatusHelp: "يُظهر هذا حالة الاتصال بنظام RAG_Project الخاص بك. تأكد من تشغيل خادم FastAPI على نقطة النهاية المكونة.",
    // SMA System
    smaActive: "Sما نشط - ذكاء الويب في الوقت الفعلي",
    smaInactive: "تفعيل SMA - مراقبة ذكية للمواقع",
    smaSearching: "SMA يبحث...",
    smaEnhanced: "استجابة محسّنة بـ SMA",
    smaWebIntelligence: "ذكاء الويب SMA",
    smaRealTimeData: "بيانات في الوقت الفعلي من ENIAD و UMP",
  }
};
